### ISSUE TITLE
NSInvalidArgumentException  Crash with Freshchat SDK 3.3.3

### ISSUE THREAD

**Issue by eonghk** [freshdesk/freshchat-ios#100] opened 2020-04-08 05:06 UTC
Hi, 
We have a crash in our iOS game and it has been there for a while. We updated the SDK to 3.3.3 but it doesn't help with it.
Here is the log from Crashlytics.

> Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x19a35096c __exceptionPreprocess
1  libobjc.A.dylib                0x19a069028 objc_exception_throw
2  CoreFoundation                 0x19a24edcc -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x19a354dc0 ___forwarding___
4  CoreFoundation                 0x19a3573a0 _CF_forwarding_prep_0
5  voyageios                      0x1034c8b44 -[FCNotificationBanner displayBannerWithChannel:]
6  voyageios                      0x10347c440 -[FCNotificationHandler showActiveStateNotificationBanner:withMessage:]
7  voyageios                      0x103474f1c +[FCMessageServices processMessageResponse:]
8  voyageios                      0x1034744c8 __55+[FCMessageServices fetchMessagesForSrc:andCompletion:]_block_invoke.155
9  libdispatch.dylib              0x199ff4b7c _dispatch_call_block_and_release
10 libdispatch.dylib              0x199ff5fd8 _dispatch_client_callout
11 libdispatch.dylib              0x19a001cc8 _dispatch_main_queue_callback_4CF
12 CoreFoundation                 0x19a2cbcc8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0x19a2c6a24 __CFRunLoopRun
14 CoreFoundation                 0x19a2c5f40 CFRunLoopRunSpecific
15 GraphicsServices               0x1a4556534 GSEventRunModal

It happens on different devices including iPhone and iPad with iOS 12.x and 13.x.

**Comment by eonghk** [comment] 2020-04-08 06:11
> FreshchatConfig *config = [[FreshchatConfig alloc]initWithAppID:@"x"  andAppKey:@"xxx"];
>     config.gallerySelectionEnabled = YES;
>     config.cameraCaptureEnabled = NO;
>     config.showNotificationBanner = YES;
>     [[Freshchat sharedInstance] initWithConfig:config];

Here is the config we use, it may help.

**Comment by harish-kumarc** [comment] 2020-04-13 12:52
Thanks for the information @eonghk , we are analysing the logs from our side to check the root cause. Are you able to replicate the issue or do you have any steps to recreate it?

**Comment by eonghk** [comment] 2020-04-16 23:38
> Thanks for the information @eonghk , we are analysing the logs from our side to check the root cause. Are you able to replicate the issue or do you have any steps to recreate it?

I do not know how to reproduce it. But it happens everyday on our customers. We can see that from our Firebase.

**Comment by harish-kumarc** [comment] 2020-04-17 13:15
Hi @eonghk , sorry for the inconvenience, we are also looking into it but failed to reproduce in dev environment so there it a little delay in taking up from our side. Will check and do necessary changes required to fix it asap. Thanks.

**Comment by eonghk** [comment] 2020-04-18 08:49
It seems to be content related. It happens when the user get the reply and the SDK is trying to push a local notification. 
This problem seems to cause another issue that users will not be able to get the replies anymore. Even we close the conversation, when it re-open, it will load the history again. Try testing those UTF8 characters like Chinese and Japanese and different images. It may cause the crash by sending a null/nil parameter to notification API. 

I am just guessing as this is not open-source. Check every parameter before call the system API. Sometimes without reproducing the issue, a fix should still be possible. You have the crash log. Make sure it doesn't crash at least. Collect some debug information when you find an illegal argument.

For a paid service, a critical issue should be fix in hours, not in days! Otherwise you should refund us.

**Comment by harish-kumarc** [comment] 2020-04-21 20:17
Hi @eonghk , Thanks for your patience. We tried possible scenarios for the crash to replicate with log trace method(s) but still no success. We need following info from your side :
1. App state (background/foreground) for crash.
2. OS crash distribution info. Is the crash happens in >= iOS 13.2.1? Reason : There was an issue in iOS fixed with 13.2.1- Apps are being aggressively killed by the OS when they go into the background state.
3. App Store link for your app. As no other customer reported the crash so we want to investigate from our side what actually create the crash in the game.
We have taken the issue with high priority and will surely release new SDK with best solution.
Thanks

**Comment by eonghk** [comment] 2020-04-22 01:13
1. It's foreground when crash happens.
2. It happens on 13.1.3, 12.1.1 and 13.1.2.
3. It only happens to users using UTF-8 characters in China for now. As you know, they have firewall and it will block SSL connections randomly. In some places, it's even worse, domains not registered in China will not be able to get visited properly.
We tried and we are not be able to reproduce this. I do not think it's product or OS version related. I would suggest not wasting time on that. You can find it on the website http://voyage.piigames.com 

It happens **only when** a user get a notification from Apple's push service and he/she is running the game. Did you find anything wrong when you review the notification code? Is it possible that a user get a push notification from Apple's server but not be able to connect to your service to fetch content? Will it cause crash if this happens?

I strongly suggest you share your notification code with me, maybe we can help.

**Comment by harish-kumarc** [comment] 2020-04-22 07:51
Thanks for the information @eonghk Will check and let you know. 
Your suggestion seems like based on the method names we have. But the flow for the crash logs mentioned is different as internally we uses some methods from the notification flow.
The flow is simple : Freshchat fetch for the messages based on the user's activity(previous support messages etc). After fetch we check if user's app is disabled for push then for selected flow we show an in app prompt for message(s).
Also we handling gracefully all nil or invalid arguments into this flow.
Thanks

**Comment by eonghk** [comment] 2020-04-24 03:15
Anyway, it happens. 
We have to switch to other products if this can not be resolved. Users are complaining.

**Comment by harish-kumarc** [comment] 2020-05-26 13:36
@eonghk we have made precautionary changes for the crash. Please update to [latest](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.6.1) SDK version.

**Closed** 2020-05-28 09:57 UTC
