### ISSUE TITLE
FCImageFragment constraints

### ISSUE THREAD

**Issue by Bran-nod** [freshdesk/freshchat-ios#39] opened 2019-05-07 09:32 UTC
Try to add image in chat. 
ios 12 
v2.4.4
```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x282846c60 FCImageFragment:0x11154adb0.width == - 2.77778e+06   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x282846c60 FCImageFragment:0x11154adb0.width == - 2.77778e+06   (active)>
```

**Comment by hemanthFW** [comment] 2019-05-08 07:10
Thanks @Bran-nod for sharing this info.
We debugged the issue from our end, it seems the breakage comes when action sheet was shown on tap of attach button. We also found that this issue happens only in iOS 12.2. 
This seems an apple [bug](https://stackoverflow.com/questions/55653187/swift-default-alertviewcontroller-breaking-constraints).
Can you please confirm the following,
- Is it happening only in iOS 12.2 devices?
- Does this happens only when Action sheet was shown?

**Comment by Bran-nod** [comment] 2019-05-08 07:19
Yep, its 12.2 but it happens sometimes(!) when I just rebuild app and open chat with images.

**Comment by hemanthFW** [comment] 2019-05-08 07:42
Can you try this scenario, just click on the attach button on the screen and let us know if the same breakage comes.
We also tried opening chat with images but we could not reproduce the issue.
We will keep an eye on the issue and update you.

**Comment by hemanth-sudarsan** [comment] 2019-08-29 09:18
@Bran-nod we could not reproduce from our end. 
Let us know if this happens still for you with latest SDK version.

**Comment by hemanth-sudarsan** [comment] 2020-02-11 11:08
@Bran-nod Closing this issue. If it happens again please reopen this thread.

**Closed by hemanth-sudarsan** 2020-02-11 11:08 UTC
