### ISSUE TITLE
Xamarin ios project not working

### ISSUE THREAD

**Issue by pallab94** [freshdesk/freshchat-ios#74] opened 2019-12-23 07:41 UTC
I have tried the below link shared with us for Xamarin ios project using freshchat sdk:

https://www.dropbox.com/sh/cdm3x9xgt7jrcpn/AACO-xpHg1imvWZIFltK6cYta?dl=0

I'm not able to open chats using proper credentials. Please provide me valid freshchat sdk project for Xamarin iOS. This is a blocker for our development.

**Comment by harish-kumarc** [comment] 2019-12-23 18:51
Hi @pallab94 , please check if dll is linked properly with above.
Please try another working sample here also please add update your appid and appkey there - https://www.dropbox.com/s/pok1adn2yl32rnq/FCiOSPushXamarin.zip?dl=0
And let us know if this works for you.

Thanks.

**Comment by pallab94** [comment] 2019-12-23 21:22
I have successfully integrated freshchat sdk and it's working now.

Few issues:

1> Freshchat.SharedInstance().UnreadCountWithCompletion((unreadCount)) 
     unreadcount always returning 0

2> sometimes sdk crashing not all times

**Comment by harish-kumarc** [comment] 2019-12-24 08:09
Awesome @pallab94 . 
For the issues above 
1. If push is enabled for sample app then unread count will reflect instantly else there is minor delay.
2. Can you please send us the exact crash logs as that will help us in getting the root cause.
Thanks

**Comment by pallab94** [comment] 2020-01-16 11:56
Hi, I have enabled push notification but still getting o in unread count.

Please go through below code and suggest if anything wrong I'm doing:

**AppDelegate FinishedLaunching**

FreshchatConfig freshchatConfig =
                    new FreshchatConfig(Constants.FreshChatAppId, Constants.FreshChatAppKey);
            freshchatConfig.GallerySelectionEnabled = true;
            freshchatConfig.CameraCaptureEnabled = true;
            Freshchat.SharedInstance().InitWithConfig(freshchatConfig);

**Setting pushtoken**

public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            // Get current device token
            var dt = deviceToken.Description;
            if (!string.IsNullOrWhiteSpace(dt))
            {
                dt = dt.Trim('<').Trim('>');
                Freshchat.SharedInstance().SetPushRegistrationToken(dt);
            }

            string msg = $"RegisteredForRemoteNotifications Firebase registration token: {dt}";
            ShowDataTransmissionAlert(msg);
        }

**Unread count code in ViewController:**

_unreadMsgObserver = NSNotificationCenter.DefaultCenter.AddObserver(new NSString("com.freshworks.freshchat_unread_message_count_changed"), ReceivedNotification, null);

private void ReceivedNotification(NSNotification notification)
        {
            CheckFreshChatUnreadMessagesCount();
        }

/// <summary>
        /// Checks freshchat unread messages count.
        /// </summary>
        public void CheckFreshChatUnreadMessagesCount()
        {
            Freshchat.SharedInstance().UnreadCountWithCompletion((unreadCount) =>
            {
                _appDelegate.ShowDataTransmissionAlert(unreadCount.ToString());

                if (onFreshChatActionListeners.Any())
                {
                    onFreshChatActionListeners.ForEach(l =>
                    {
                        l.OnUnreadMessageCountUpdated((int)unreadCount);
                    });
                }
            });
        }


unreadCount always returning 0.

**Comment by pallab94** [comment] 2020-01-16 12:04
FYI...I'm using Firebase Cloud Messaging for push notification.

**Comment by harish-kumarc** [comment] 2020-01-16 12:17
Hi @pallab94 , Are you able to get push notifications into your application for agent conversation(s) after implementation? As prompt display of unread count is linked with push notifications.

To receive push you must add correct environment certificate(with bundlId and password) in Freshchat portal under Settings -> Mobile SDK. Also please check Push enabled flag value for conversation 
<img width="393" alt="Screenshot 2020-01-16 at 5 41 41 PM" src="https://user-images.githubusercontent.com/16202319/72524237-7ac9b000-3887-11ea-9d83-c3402136533d.png">
If the flag is No then please check implementation as it refers the the target device token itself is not available with Freshchat.
For iOS, we get p12 so that our servers connect to APNS directly and send notifications, not link with firebase for push.

**Comment by pallab94** [comment] 2020-01-16 12:32
<img width="344" alt="Screenshot 2020-01-16 at 5 52 25 PM" src="https://user-images.githubusercontent.com/59161402/72525475-4277a100-388a-11ea-97db-a1c0303a16c9.png">
<img width="938" alt="Screenshot 2020-01-16 at 6 00 12 PM" src="https://user-images.githubusercontent.com/59161402/72525476-4277a100-388a-11ea-9db5-7a0dff29f154.png">

Please check attached settings. I already added proper certificate.

**Comment by harish-kumarc** [comment] 2020-01-16 12:36
Is push notifications are working for you?

**Comment by pallab94** [comment] 2020-01-16 12:39
yes I'm receiving push notifications from Server as well as FCM

**Comment by harish-kumarc** [comment] 2020-01-17 06:44
Hi @pallab94, here is the link for the sample project for unread count https://www.dropbox.com/s/lepbdrvjbqf9n28/UnreadCountiOSSample.zip?dl=0 Please check and let us know if it works for you.

**Comment by harish-kumarc** [comment] 2020-02-11 17:07
Closing the issue, let us know if you are still facing the issue.

**Closed by harish-kumarc** 2020-02-11 17:07 UTC
